### ISSUE TITLE
Chapter cover disable extraction

### ISSUE THREAD

**Issue by edgehub-cloud** [zachstultz/komga-cover-extractor#1]

**Comment by zachstultz** [comment]
Implemented, update settings and set extract_chapter_covers in settings.py https://github.com/zachstultz/komga-cover-extractor/commit/009b7355aedf6b4cb35a96eb454ecebefb0227a5 https://github.com/zachstultz/komga-cover-extractor/commit/aa3f5797495337531f93d985d779d9265e493c4e
