### ISSUE TITLE
yet another issue

### ISSUE THREAD

**Issue by edgehub-cloud** [zachstultz/komga-cover-extractor#3]
Similarity between: "yamada kun seven witches" and "yamada kun seven witches" Score: 1.0 out of 1.0

        Required Folder Matching Percent: 90%
                Download Folder CBZ Percent: 100.0%
                Existing Folder CBZ Percent: 100.0%

                Download Folder EPUB Percent: 0%
                Existing Folder EPUB Percent: 0%

                Download Folder Chapter Percent: 0%
                Existing Folder Chapter Percent: 0%

                Download Folder Volume Percent: 100.0%
                Existing Folder Volume Percent: 100.0%

                Found existing series from cache: /home/ubuntu/manga/Yamada-kun and the Seven Witches
Traceback (most recent call last):
  File "/home/ubuntu/komga/manga.py", line 6701, in <module>
    main()
  File "/home/ubuntu/komga/manga.py", line 6679, in main
    check_for_existing_series()
  File "/home/ubuntu/komga/manga.py", line 3554, in check_for_existing_series
    done = check_upgrade(
  File "/home/ubuntu/komga/manga.py", line 2910, in check_upgrade
    + array_to_string(volume.volume_number, ",")
  File "/home/ubuntu/komga/manga.py", line 2661, in array_to_string
    return separator.join(array)
TypeError: sequence item 0: expected str instance, float found
➜  ubuntu gdu mangaRss

**Comment by zachstultz** [comment]
First issue is fixed, I couldn't replicate the second issue so I added a safeguard check before pulling the file sizes: https://github.com/zachstultz/komga-cover-extractor/commit/92804755e04f3c4f65b1e83f9112e468edb8bfb3
