### ISSUE TITLE
 I find two problems

### ISSUE THREAD

**Issue by grove5** [zachstultz/komga-cover-extractor#4]
It's my first time writing on github, so I apologize if I do something wrong. I find two problems with the script:

1. Does not generate a cover.jpg for cbz files.
2. Only works when there is a single cbz file in the path. When I use the script in a path with several .cbz files, it returns the error "IndexError: list index out of range".

I don't know if it's a script error or I'm doing something wrong. Greetings and thanks for developing this good idea.

**Comment by zachstultz** [comment]
How are you naming your files? Either take a screenshot of the directory where the files aren't generating a cover.jpg and it's only working with a single file and kindly post that, or list me the file names for the affected directory, this will allow me to replicate the file names on my end and see if I can replicate the issue as it could just be a naming issue for the first problem.

**Comment by grove5** [comment]
Here is an example. I run the script twice in the same directory, the first time with 2 .cbz files and the second time with only 1 file. In the first case it returns the error "IndexError: list index out of range" and does not generate images in the directory, in the second case it works without problems. In neither case does it generate a cover.jpg file. Next I leave images of the terminal and the directory for both cases. I hope it helps.
![Terminal 2 files](https://user-images.githubusercontent.com/99394790/218328822-c319600c-97f5-4020-b7a0-c19facd93692.PNG)
![Path 2 files](https://user-images.githubusercontent.com/99394790/218328839-e565987a-d16c-4ad1-8717-de8f8307e7d8.png)
![Terminal 1 file](https://user-images.githubusercontent.com/99394790/218328848-432212ce-8b08-4ca5-8bc6-a78f5cac0654.png)
![Path 1 file](https://user-images.githubusercontent.com/99394790/218328851-6c892f60-7d10-4948-89bf-ba354518a659.png)

**Comment by zachstultz** [comment]
Absolutely excellent response, from the file list, exact error output, and the exact command you were sending. It truly does make hunting down the bug easier 👍

Give the new version a go, it should all be fixed, but let me know if it still persists or if you run into anything unexpected.

**Comment by grove5** [comment]
Thank you so much! I am amazed at the speed with which you fixed the problem. I've tried it and it works perfectly. It still doesn't generate a cover.jpg file, but I prefer it that way since I don't always choose the cover of the first volume as the cover for Komga.

Again I thank you for such a good job.

**Comment by zachstultz** [comment]
Glad to have fixed the first issue, I will leave the issue open as the second one still remains, I will try to investigate it further and see if I can replicate it on my end.
